---
title: "About"
author: "Christopher Peters"
date: "June 26, 2015"
output: html_document
---
from adverse events related to medicine listed in the API, so I hope you'll agree that public awareness and understanding of the risks associated with medical drugs are a worthy endeavor.

<i>Note: the FDA <a href="http://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/ucm070461.htm">reports 117,752 deaths in the database in just 2013</a>, so the number above [may even understate the total number of deaths from advese events](https://api.fda.gov/drug/event.json?search=&count=patient.reaction.reactionoutcome).</i>

### FDA Adverse Event Reporting System (FAERS)

The <a href="http://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/">FDA FAERS system</a> is a database of adverse events (basically, drug reactions and medication error reports). The FDA uses the database in its post-marketing surveillance program.

### OpenFDA

In early 2014, <a href="https://open.fda.gov/update/introducing-openfda/">the FDA released an API</a> to make adverse event reports, labels, and eforcement reports more accessible.

Previously, these files only existed <a href="http://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/ucm082193.htm">as flat files on the FDA website.</a> If you'd like to access the entirety of the data shown in this dashboard, these files are a good start -- though they generally lag by six months (today (6/27/15), the latest available data is from 2014).

### People who deserve credit

Taha A. Kass-Hout, MD, MS, Chief Health Informatics Officer of FDA
for leading the FDA team to publish the OpenFDA API.
-  taha@fda.hhs.gov
-  [@DrTaha_FDA](https://twitter.com/DrTaha_FDA)

[Contributors](https://github.com/FDA/openfda/graphs/contributors) to the OpenFDA project.

[Contributors](https://github.com/rOpenHealth/openfda/graphs/contributors) to the [rOpenHealth](https://github.com/rOpenHealth) R package for [making working with the API in R a pleasure](https://github.com/ropenhealth/openfda).

The Rstudio team for <a href="http://shiny.rstudio.com/">their awesome web application framework for R</a>, Shiny.

[Paul H. C. Eilers](http://portal.uc3m.es/portal/page/portal/conocenos/chairs_excellence/chairs_excel_14/paul_eilers) and [Brian D. Marx](http://www.stat.lsu.edu/faculty/marx/) for the Smoothing spline method used on weekly report counts: ["Flexible smoothing with B-splines and penalties"](http://projecteuclid.org/euclid.ss/1038425655)

### R packages used
-  Shiny [https://github.com/rstudio/shiny-server](https://github.com/rstudio/shiny-server)
-  rOpenSci/openfda [https://github.com/ropenhealth/openfda](https://github.com/ropenhealth/openfda)
-  ggplot2 [https://github.com/hadley/ggplot2](https://github.com/hadley/ggplot2)
-  scales [https://github.com/hadley/scales](https://github.com/hadley/scales)
-  dplyr [https://github.com/hadley/dplyr](https://github.com/hadley/dplyr)
-  reshape2 [https://github.com/hadley/reshape](https://github.com/hadley/reshape)
-  ggthemes [https://github.com/jrnold/ggthemes](https://github.com/jrnold/ggthemes)
